services:
  mysql:
    image: mysql:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: alterbooth
      MYSQL_USER: alterbooth
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p $$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  fastapi:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back/src:/back
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 3s
    depends_on:
      mysql:
        condition: service_healthy

  front:
    image: node:latest
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "8080:8080"
    command: ["npx", "serve", ".", "-l", "8080"]
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      fastapi:
        condition: service_healthy

  nginx:
    image: nginx:1.27.1
    ports:
      - "80:80"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 3s
    volumes:
      - ./docker/nginx/config/dev_default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      front:
        condition: service_healthy

  tunnel:
    restart: always
    image: cloudflare/cloudflared
    command: tunnel run
    env_file:
      - ./.env
    depends_on:
      nginx:
        condition: service_healthy