DROP TABLE IF EXISTS target;


CREATE TABLE target(
    target_id INT PRIMARY KEY AUTO_INCREMENT,
    target VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);